app:
  replicaCount: 3
  image:
    repository: codeykenny/github-actions-learn-2
    tag: "ccc2f4f800227e6f7d74bd57637f1d23e239e57f"
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 5000
    targetPort: 5000
    nodePort: 30501

mysql:
  replicaCount: 1
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  service:
    port: 3306
    targetPort: 3306
  storage:
    size: 1Gi
    accessMode: ReadWriteOnce
